name: Build

on:
  push:
    branches:
      - master

    tags:
      - v*

jobs:
  job:
    name: ${{ matrix.os }} (${{ matrix.cxx }}, ${{ matrix.buildtype }})
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      max-parallel: 8
      matrix:
        name: [ ubuntu-gcc, ubuntu-clang, macos-gcc, macos-clang ]
        buildtype: [ Debug, Release ]
        include:
          - name: ubuntu-gcc
            os: ubuntu
            cxx: g++
            cc: gcc
            triplet: x64-linux
          - name: ubuntu-clang
            os: ubuntu
            cxx: clang++
            cc: clang
            triplet: x64-linux
          - name: macos-gcc
            os: macos
            cxx: g++
            cc: gcc
            triplet: x64-osx
          - name: macos-clang
            os: macos
            cxx: clang++
            cc: clang
            triplet: x64-osx

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Get latest CMake version
        # Using 'latest' branch, the latest CMake is installed.
        uses: lukka/get-cmake@latest

      - name: Set Environment vars
        run: |
          echo "CXX=${{ matrix.cxx }}" >> $GITHUB_ENV
          echo "CC=${{ matrix.cc }}" >> $GITHUB_ENV

      - name: Build with CMake
        uses: lukka/run-cmake@main
        with:
          useVcpkgToolchainFile: true
          buildDirectory: ${{ runner.workspace }}/build/${{ matrix.buildtype }}
          cmakeBuildType: ${{ matrix.buildtype }}
